version: '3.4'

services:
  librarymanagement.api:
    image: ${DOCKER_REGISTRY-}librarymanagementapi
    build:
      context: .
      dockerfile: src/LibraryManagement.Api/Dockerfile
    extra_hosts:
    - "host.docker.internal:host-gateway"
